### model
model_name_or_path: ckpt/Qwen2.5-VL-7B-Instruct-add-token
quantization_bit: 4  # choices: [8 (bnb/hqq/eetq), 4 (bnb/hqq), 3 (hqq), 2 (hqq)]
quantization_method: bnb  # choices: [bnb, hqq, eetq]
trust_remote_code: true
image_max_pixels: 200704
image_min_pixels: 3136

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all
#additional_target: embed_tokens,lm_head
#deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset_dir: data
dataset: nuscenes_drivelm_train
eval_dataset: nuscenes_drivelm_val
template: qwen2_vl
cutoff_len: 4096

max_samples: 100
overwrite_cache: false
tokenized_path: data/cache/nuscenes_drivelm
preprocessing_num_workers: 8
dataloader_num_workers: 8

#streaming: True
#max_steps: 100
#buffer_size: 128
#preprocessing_batch_size: 128
#preprocessing_num_workers: 8
#dataloader_num_workers: 8
#accelerator_config:
#  dispatch_batches: false

### output
output_dir: output/Qwen2.5-VL-7B-Instruct-add-token/debug
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

## eval
#val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
